# Site settings
title: London R-Dojo Blog
description: > # this means to ignore newlines until "baseurl:"
  London R coding dojo blog.
baseurl: "https://london-r-dojo.github.io/_site" # the subpath of your site, e.g. /blog/
url: "http://www.meetup.com/LondonR/" # the base hostname & protocol for your site
github_username:  london-r-dojo.github.io
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
